filebeat.inputs:
- type: filestream
  id: filebeat-postgres-logs
  paths:
    - /var/lib/postgresql/data/log/*.log
  index: filebeat-postgres-logs

output.logstash:
  hosts: ["logstash:5013", "logstash:5014"]