version: "3.9"

services:
  # linux-server:
  #   build:
  #     context: linux-server
  #     dockerfile: Dockerfile
  #   container_name: linux-server
  #   hostname: linux-server
  #   ports:
  #     - 2222:22
  #   logging:
  #     driver: "gelf"
  #     options:
  #       gelf-address: "udp://localhost:5000"
  #       tag: "linux-server"

  # web-server:
  #   build: 
  #     context: web-server
  #     dockerfile: Dockerfile
  #   container_name: web-server
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000
  #   volumes:
  #       - ./web-server/app:/app
  #   ports:
  #     - 8000:8000

  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    
networks:
  default:
    name: elk
    external: true