version: "3.9"

networks:
  default:
    name: elk
    external: true

services:
  linux-server:
    build:
      context: linux-server
      dockerfile: Dockerfile
    container_name: linux-server
    hostname: linux-server
    ports:
      - 2222:22

  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: database
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../logs/database:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-server:
    build: 
      context: web-server
      dockerfile: Dockerfile
    container_name: web-server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
    volumes:
        - ./web-server/app:/app
        - ../logs/web-server:/var/log/app
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  beat:
    build:
      context: beat
      dockerfile: Dockerfile
    container_name: beat
    environment:
      - DATABASE_SERVER=database
      - LINUX_SERVER=linux-server
      - WEB_SERVER=web-server
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:5091"
        tag: "beat"
