- pipeline.id: database-beat
  path.config: "/usr/share/logstash/pipeline/database-beat.conf"

- pipeline.id: database
  path.config: "/usr/share/logstash/pipeline/database.conf"

- pipeline.id: linux-server
  path.config: "/usr/share/logstash/pipeline/linux-server.conf"
