- pipeline.id: database-beat
  path.config: "/usr/share/logstash/pipeline/database-beat.conf"

- pipeline.id: database
  path.config: "/usr/share/logstash/pipeline/database.conf"

- pipeline.id: linux-server
  path.config: "/usr/share/logstash/pipeline/linux-server.conf"

- pipeline.id: web-server
  path.config: "/usr/share/logstash/pipeline/web-server.conf"

- pipeline.id: web-server-beat
  path.config: "/usr/share/logstash/pipeline/web-server-beat.conf"
  
- pipeline.id: windows-server
  path.config: "/usr/share/logstash/pipeline/windows-server.conf"
