#disable ilm
setup.ilm.enabled: false

setup.template.name: "linux-filebeat"
setup.template.pattern: "linux-filebeat-*"
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "linux-filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

filebeat.modules:
- module: system
  syslog:
    enabled: true
    var.paths: ["/var/log/syslog*"]
  auth:
    enabled: true
    var.paths: ["/var/log/auth.log*"]

# setup.kibana:
#   host: "kibana:5601"
